name: Publish lightning-talk
on:
  push:
    branches: [ master ]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: yarn build
      - name: Cache app-build
        uses: actions/cache@v2
        with:
          path: './dist'
          key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
  publish:
    name: Publish to netlify
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Cache app-build
      uses: actions/cache@v2
      with:
        path: './dist'
        key: ${{ runner.os }}-app-${{ hashFiles('yarn.lock') }}
    - name: Netlify Actions
      uses: nwtgck/actions-netlify@v1.2.2
      with:
        publish-dir: './dist'
        production-branch: master
        github-token: ${{ secrets.TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
        overwrites-pull-request-comment: true
        github-deployment-environment: "Deploy"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
